# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('pokes_app', '0002_poke_pokes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='poked',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='poker',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='pokes',
        ),
        migrations.AddField(
            model_name='poke',
            name='pokes',
            field=models.ManyToManyField(related_name='pokers', to='login_app.User'),
        ),
    ]
