# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokes_app', '0003_auto_20170928_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='pokes',
            field=models.ManyToManyField(related_name='poker', to='login_app.User'),
        ),
    ]
